#!/bin/sh

FILENAME=robot.Main

# Java
cd src/main/java
java $FILENAME "$@"

# Scala
# scala $FILENAME "$@"

# C#
# mono $FILENAME.exe "$@"

# Ruby
# ruby $FILENAME.ruby "$@"

# Python
# python $FILENAME.py "$@"

# Javascript
# node $FILENAME.js "$@"

# Haskell
# ./$FILENAME "$@"
